---
- src: git@github.com:wintercomesX/clickhouse-role.git
  scm: git
  version: "1.0.0"
  name: clickhouse-role

- src: git@github.com:wintercomesX/vector-role.git
  scm: git
  version: "1.0.0"
  name: vector-role

- src: git@github.com:wintercomesX/lighthouse-role.git
  scm: git
  version: "1.0.0"
  name: lighthouse-role
