---
- name: Install ClickHouse
  hosts: clickhouse
  become: true
  roles:
    - clickhouse-role

- name: Install and configure Vector
  hosts: vector
  become: true
  roles:
    - vector-role

- name: Install and configure LightHouse
  hosts: lighthouse
  become: true
  roles:
    - lighthouse-role
